nama_lengkap = input("Nama Lengkap:")
nama_panggilan = input("Nama Panggilan:")
nim = str(input("Masukkan NIM:"))
prodi = input("Masukkan Prodi")
umur = str(input("Masukkan Umur:"))
asal_sekolah = input("Masukkan Asal Sekolah:")
asal_kota = (input("Masukkan Asal Kota:"))
alasan_masuk_informatika = input("Masukkan Alasan Masuk Informatika:")

modulus_tiga_nim_terakhir = int(str(nim)[-3:])

print(f" Perkenalkan Nama saya {nama_lengkap}.")
print(f" Biasa Dipanggil {nama_panggilan}.")
print(f" Dengan NIM {nim}.")
print(f" Tiga NIM terakhir saya {modulus_tiga_nim_terakhir}")
print(f" Saya Dari Program Studi {prodi}.")
print(f" Umur Saya {umur}.")
print(f" Asal Sekolah Saya Dari {asal_sekolah}.")
print(f" Asal Kota Saya {asal_kota}.")
print(f" Alasan Saya Masuk Informatika {alasan_masuk_informatika}.")